### ISSUE TITLE
Check if the "weights" setting is being used correctly

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#374]
**Description of the error**
Some jobs have the weight setting available to be used such as the radius of gyrations. However, by looking at the code it is not being used at all. 

In other cases it does not seem to be applied correctly for example in the eccentricity job. The weight factor is only applied to the moment of inertia result but it replaces the mass in the moment of inertia with the weight factor so that the weight factor means that it is not a moment of inertia anymore. It also does not follow the documentation in anyway.

**Suggested fix**
Go through all jobs and try to make sure that it follows what is described in the documentation https://mdanse.readthedocs.io/en/protos/pages/parameters.html#weights and that applying the weighting makes sense or that if doesn't make sense to have weighting it should not be included.

Perhaps the weight setting should be applied for all cases where a mean of some sort is done e.g. RMSD should include the weight setting. 

Jobs to check
---------------

**Dynamics**
- [ ] AngularCorrelation
- [x] #411
- [ ] GeneralAutoCorrelationFunction
- [x] MeanSquareDisplacement
- [ ] OrderParameter
- [x] PositionAutoCorrelationFunction
- [x] VelocityAutoCorrelationFunction
- [x] #689 (van Hove distinct)
- [x] van Hove self

**Structure**
- [x] AreaPerMolecule (weight scheme not used)
- [x] DensityProfile
- [x] #378 (weight scheme not used)
- [x] MolecularTrace (weight scheme not used)
- [ ] #591
- [x] #381 (weight scheme not used)
- [x] RootMeanSquareFluctuation (weight scheme not used)
- [x] SolventAccessibleSurface (weight scheme not used)
- [x] Voronoi (weight scheme not used)
- [x] #689 (CoordinationNumber)
- [x] #689 (PDF)
- [x] #689 (SSF)
- [x] #689 (X-Ray) (weight scheme not used)

**Scattering**
- [x] #689 (CCF)
- [x] #689 (DCSF)
- [x] #537 (DISF)
- [x] #537 (EISF)
- [x] #537 (GDISF)
- [x] #689 (NDTSF)
- [x] #766 (SFFSF)

**Thermodynamics**
- [x] Density (weight scheme not used)
- [x] Temperature (weight scheme not used)

**Infrared**
- [x] Infrared (weight scheme not used)
- [x] DipoleAutoCorrelationFunction (weight scheme not used)

**Virutal Instruments**
- [ ] McStasVirtualInstruments

**Comment by ChiCheng45** [comment]
Density and temperature do not have a weights setting this makes sense to me.

**Comment by ChiCheng45** [comment]
Closing as I think this has mostly been sorted or other issues are open for them.
